# Generated by Django 4.1.2 on 2022-10-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmdata",
            name="type",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
