# Generated by Django 4.1.2 on 2022-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("film", "0002_filmdata_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmdata",
            name="image",
            field=models.ImageField(
                default="Images/image_placeholder.jpg", upload_to="Images/"
            ),
        ),
    ]
